name: Sync from upstream

on:
  schedule:
    - cron: '0 2 * * *' # 每天 02:00 UTC 运行
  workflow_dispatch: # 手动触发工作流

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false # 使用自定义认证

      - name: Set up Git
        run: |
          git config user.name "zcvic"
          git config user.email "2484068670@qq.com"

      - name: Add upstream repository
        run: git remote add upstream https://github.com/NapNeko/napneko.github.io.git # 替换为源仓库的URL

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main # 切换到主分支
          git merge upstream/main --allow-unrelated-histories -X theirs # 合并源仓库分支并允许不同历史

      - name: Update remote URL
        run: git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/zcvic/napneko.github.io.git # 替换为您的 GitHub 用户名和仓库名

      - name: Push changes to origin
        run: git push origin main
