name: Update Forked Repository

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch: 

jobs:
  update-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Forked Repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Add Upstream Repository
        run: |
          git remote add upstream https://github.com/NapNeko/napneko.github.io.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
